Update ani-cli

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -83,7 +83,7 @@ version_info() {
 }
 
 update_script() {
-    update="$(curl -s -A "$agent" "https://raw.githubusercontent.com/pystardust/ani-cli/master/ani-cli")" || die "Connection error"
+    update="$(curl -s -A "$agent" "https://github.com/candrapersada/ani-cli-yt-dlp/master/ani-cli")" || die "Connection error"
     update="$(printf '%s\n' "$update" | diff -u "$0" -)"
     if [ -z "$update" ]; then
         printf "Script is up to date :)\n"
@@ -226,7 +226,9 @@ update_history() {
 download() {
     case $1 in
         *m3u8*)
-            if command -v "yt-dlp" >/dev/null; then
+            if command -v "N_m3u8DL-RE" >/dev/null; then
+                N_m3u8DL-RE --log-level ERROR --thread-count 16 --download-retry-count 999 "$1" --tmp-dir "${HOME}/yt-dlp_temp" --save-dir "$download_dir" --save-name "$2"
+            elif command -v "yt-dlp" >/dev/null; then
                 yt-dlp "$1" --no-skip-unavailable-fragments --fragment-retries infinite -N 16 -o "$download_dir/$2.mp4"
             else
                 ffmpeg -loglevel error -stats -i "$1" -c copy "$download_dir/$2.mp4"
